services:
  backend:
    container_name: grubhunter-backend
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: grubhunter
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/grubhunter-backend/seed-mongodb.js:/docker-entrypoint-initdb.d/seed-mongodb.js
      - mongodb_data_container:/data/db
  application:
    container_name: grubhunter-application
    image: node:lts-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./code:/home/node/code
    working_dir: /home/node/code/grubhunter
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    tty: true
    command: "npm run dev"
volumes:
  mongodb_data_container: